### ISSUE TITLE
Can you provide a simple creative commons license to the mapping files?

### ISSUE THREAD

**Issue by matentzn** [emcarthur/phecode-HPO-map#1]
It would be amazing if you could consider adding an explicit license to your mappings, like CC-BY 4.0 or even better, CC-0 so we can re-use your work in other projects.

Thank you for considering.

**Comment by emcarthur** [comment]
The mappings are available with CC0 here: https://datadryad.org/stash/dataset/doi:10.7272%2FQ6H70D20 I have added the MIT License to the code/software mappings here in GitHub. Thanks

**Comment by matentzn** [comment]
This is fantastic @emcarthur Thank you!
